# Generated by Django 3.1.7 on 2021-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('parsed', models.CharField(max_length=200)),
                ('hints', models.CharField(max_length=200)),
                ('_links', models.CharField(max_length=200)),
            ],
        ),
    ]
