# Generated by Django 3.1.7 on 2021-03-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='veggie_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
