# Generated by Django 3.1.7 on 2021-03-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableGame', '0002_auto_20210329_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='veggie_answer',
            field=models.BooleanField(default=True),
        ),
    ]
