# Generated by Django 3.1.7 on 2021-04-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableGame', '0003_auto_20210329_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_questions', to='vegetableGame.question'),
        ),
    ]
