# Generated by Django 3.1.7 on 2021-04-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
